/**
 * Authoritative Master Catalog of ATA Member Seminaries & Theological Institutions (202 Total).
 * Strictly sourced from official ATA accreditation records.
 * DO NOT hardcode new values or omit existing institutions.
 */

export const INSTITUTION_NAMES: string[] = [
  "Academy for Church Planting & Leadership",
  "Academy for Theology and Missions",
  "Academy of Integrated Christian Studies",
  "ACTS Academy of Higher Education",
  "AG Tamilnadu Bible College",
  "AGAPE College",
  "All Nations Theological Seminary",
  "Allahabad Bible Seminary",
  "Amazing Grace Biblical Seminary",
  "Amazing Grace Theological Seminary",
  "Anderson Theological College",
  "Andhra Bible College",
  "Andhra Christian Theological College",
  "Andhra Pradesh Bible College",
  "Antioch Biblical Seminary and College",
  "Antioch Center for Theological Studies",
  "Aroma Bible College",
  "Arunachal Theological college",
  "Asia Antioch Seminary",
  "Asia Evangelical College & Seminary",
  "Asia Graduate School of Theology - North East India (AGST-NEI)",
  "Asia Graduate School of Theology-North East India",
  "Asian Bible College",
  "Asian Christian College of Theology",
  "Baptist Bible College & Seminary",
  "Baptist Seminary of South India",
  "Baptist Theological College & Seminary",
  "Berachah Institute of Higher Education and Research",
  "Berean Baptist Bible College & Seminary",
  "Bethel New Life College",
  "Bethesda Biblical Seminary",
  "Biblical Theological College & Seminary",
  "Brethren Bible Institute",
  "Buntain Theological College",
  "Calcutta Bible College",
  "Calcutta Bible Seminary",
  "Caleb Institute",
  "Calvin Theological College & Seminary",
  "Carmel Bible College",
  "Central India Theological Seminary",
  "Centre for Global Leadership Development (SABC & GSOL)",
  "Chil Chil Baptist College & Seminary",
  "Christ Commission Discipleship Institute",
  "Christ for the Nations Bible College",
  "Christian Academy for Advanced Theological Studies",
  "Christian Leadership Development Centre",
  "Christian Renewal Theological Seminary",
  "Church On The Rock Theological Seminary",
  "City to City India Trust",
  "Clark Theological College",
  "Compel Outreach Bible College",
  "Cornerstone Bible College & Training Centre",
  "Covenant Institute of Theology and Mission",
  "Covenant International Bible College",
  "Delhi Bible Institute",
  "Discipleship Bible College",
  "Discipleship Theological Seminary",
  "Dobam Theological College",
  "Doon Bible College",
  "Doulos Bible Institute",
  "Doulos Theological College",
  "Eastern Bible College",
  "Eastern Theological College",
  "Eastern Theological Institute & Seminary",
  "Ebenezer Bible College",
  "Ebenezer Theological Seminary",
  "Ecclesia Theological College & Seminary",
  "Evangelical College of Theology",
  "Evangelical Theological Seminary",
  "Faith Baptist Bible College & Seminary",
  "Faith Theological Seminary",
  "Federated Theology Program of North East India (FTP – NEI)",
  "Filadelfia Institute of Global Studies (FIGS)",
  "Focus India Theological College",
  "Full Gospel Bible College",
  "Global Leadership Training Centre",
  "Golden Crown Theological College",
  "Grace Bible College",
  "Great Harvest Theological Institute",
  "Green Pastures Theological Centre",
  "Harvest Bible",
  "Harvest Bible College",
  "Harvest Mission Bible College",
  "Harvest Mission College",
  "Harvesters Theological College & Seminary",
  "Hebron Gospel Theological College & Seminary",
  "Heritage Baptist Bible College & Seminary",
  "Himalayan Institute of Leadership Training",
  "Hindustan Bible Institute & College",
  "Huldah Buntain Theological College",
  "Hyderabad Bible College",
  "Hyderabad Institute of Theology and Apologetics",
  "Ichthoos Bible College",
  "Immanuel Theological Seminary",
  "India Baptist Theological Seminary",
  "India Bible College & Seminary",
  "India Centre for Leadership",
  "India Christian Bible College",
  "India Full Gospel Bible College",
  "India Graduate School of Missiology",
  "India St. Thomas Bible College & Seminary",
  "Institute for Biblical Studies",
  "IPC Theological Seminary",
  "John's Leadership Institute",
  "Jubilee Memorial Bible College",
  "Karnataka Bible College",
  "Karunya Academy for Theological Education (KATE)",
  "Kerala Baptist Bible College & Seminary",
  "Kerala Christian Theological Seminary",
  "Kihoto Theological College",
  "Kor-In Theological College & Seminary",
  "Lakeview Bible College and Seminary",
  "Lamb's Institute of Field Evangelism",
  "Lamb’s Institute of Field Evangelism",
  "Leadership Theological College International",
  "Life Theological Seminary",
  "Life Transforming College International",
  "Living Bible College",
  "Living Hope Theological Seminary",
  "Logos College",
  "Logos College of Advanced Studies",
  "Madras AG Bible College",
  "Madras Assemblies of God Bible College",
  "Madras Theological Seminary & College",
  "Maharastra Bible college",
  "Mahima Bible Institute",
  "Manna Bible College",
  "Maranatha Biblical Seminary",
  "Maranatha Theological Seminary",
  "Maranatha Veda Patasala",
  "Mission India Bible college",
  "Mission India Theological Seminary",
  "Mizoram Bible College",
  "Mt Terogvu Theological College",
  "Mt. Terogvu Theological College",
  "Mt. Zion Bible Seminary",
  "Nagaland Baptist College",
  "Nagaland Bible College",
  "Native Evangelical School of Theology",
  "Nav Bharat Bible Institute",
  "Navin Doman Theological College",
  "New Creation Theological Academy",
  "New Hope Bible College",
  "New India Bible Seminary",
  "New life Bible College",
  "New Life Biblical Seminary",
  "New Life College",
  "New Life School of Mission",
  "New Theological College",
  "Ngulhao Theological Seminary",
  "Nichols-Roy Bible College",
  "Nito Theological College",
  "North East India Baptist Bible College & Seminary",
  "North East Theological Seminary",
  "North India College of Christian Studies",
  "North India Institute of Theological Studies",
  "Oriental Theological College",
  "Oriental Theological Seminary",
  "Peniel Bible Seminary",
  "Presbyterian Theological Seminary",
  "Punjab Bible College",
  "Reachout Theological Seminary",
  "Rehoboth Theological Institute",
  "Restoration Theological College",
  "Rhema Bible College and Seminary",
  "Rhema Revival Bible College",
  "Sathya Veda Seminary",
  "SATYA VACHAN SEMINARY",
  "Servanthood Bible College",
  "Shalom Bible College",
  "Shalom Bible Seminary",
  "Sharon Bible College",
  "Shiloh Baptist Bible College & Seminary",
  "Sielmat Bible College",
  "South Asia Institute of Advanced Christian Studies (SAIACS)",
  "South Asia Leadership Training and Development Centre, (SALT-DC)",
  "South Asia Nazarene Bible College",
  "South Asia Theological College and Seminary",
  "South Asian Institute for Leadership and Cultural Studies (SAILCS)",
  "South India Baptist Bible College & Seminary",
  "South India Bible Seminary, (SIBS)",
  "Southern Asia Leadership Institute",
  "Southern Bible College",
  "St. Ignatius Theological Seminary",
  "Susamachar Theological College & Seminary - Copy",
  "Susamachar Theological College and Seminary",
  "The Salvation Army Human Resource Development Department in India",
  "The Word for The World International",
  "Trinity Bible College",
  "Trinity Christian College",
  "Trinity College and Seminary",
  "Trinity Theological College",
  "Trivandrum Biblical Seminary",
  "True Light for Asia Biblical Seminary",
  "UIM-Family Research Training Institute (UIM-FRTI)",
  "Union Biblical Seminary",
  "United College of Theology & Missions",
  "Universal Institute of Truth",
  "Vellore Bible College",
  "Vision Theological Seminary",
  "Witter Bible College",
  "Zion Bible College"
];
