/**
 * Authoritative Master Catalog of ATA Programs and Courses (127 Total).
 * Strictly sourced from the official ATA syllabus & curriculum standards.
 * DO NOT hardcode new values or omit existing programs.
 */

export const PROGRAM_NAMES: string[] = [
  "B.A in Christian Ministry & Leadership",
  "B.R.E",
  "Bachelor",
  "Bachelor of Arts",
  "Bachelor of Arts in Christian Music",
  "Bachelor of Ministry (Distance Education)",
  "Bachelor of Theology",
  "Bachelor of Theology (Bi-Lingual - English/Hindi)",
  "Bachelor of Theology (Bi-lingual English & Hindi)",
  "Bachelor of Theology (Bi-lingual)",
  "Bachelor of Theology (Distance Education)",
  "Bachelor of Theology (Distance Learning)",
  "Bachelor of Theology (English-Campus based program)",
  "Bachelor of Theology (English-Res)",
  "Bachelor of Theology (English-Residential)",
  "Bachelor of Theology (English)",
  "Bachelor of Theology (Evening College)",
  "Bachelor of Theology (Malayalam, English)",
  "Bachelor of Theology (Malayalam)",
  "Bachelor of Theology (Non-residential)",
  "Bachelor of Theology (Regular)",
  "Bachelor of Theology (Res & Non-Res)",
  "Bachelor of Theology (Res-Bilingual [Eng & Telu])",
  "Bachelor of Theology (Res-English)",
  "Bachelor of Theology (Res)",
  "Bachelor of Theology (Residential)",
  "Bachelor of Theology (Tamil-Res & Modular)",
  "Bachelor of Theology (Tamil)",
  "Bachelor of Theology (Telugu & English)",
  "Certificate",
  "Certificate in Ministry",
  "Certificate in Pracharak Studies (Hindi)",
  "Certificate in Theology",
  "Certificate in Theology (Hindi)",
  "Certificate in Theology (Res-English)",
  "Certificate of Theology",
  "Diploma",
  "Diploma in Christian Ministry",
  "Diploma in Christian Ministry (English & Tamil)",
  "Diploma in Theology",
  "Diploma in Theology (English & Kannada)",
  "Diploma in Theology (English-Campus based program)",
  "Diploma in Theology (English-Residential)",
  "Diploma in Theology (English)",
  "Diploma in Theology (Hindi & English)",
  "Diploma in Theology (Malayalam & English)",
  "Diploma in Theology (Malayalam)",
  "Diploma in Theology (Marati)",
  "Diploma in Theology (Res-English)",
  "Diploma in Theology (Res-Telugu)",
  "Diploma in Theology (Residential)",
  "Diploma in Theology (Tamil-Res & Extn)",
  "Diploma in Theology (Tamil)",
  "Diploma in Theology (Telugu & English)",
  "Doctor of Ministry",
  "Doctor of Ministry (DL)",
  "Doctor of Ministry (Online)",
  "Doctor of Philosophy (Integrated)",
  "Doctor of Philosophy (PhD)",
  "Doctor of Theology",
  "Doctoral",
  "Integrated PhD",
  "M.R.E",
  "MA (online)",
  "MA in Christian Studies",
  "MA in Christian Studies (Online)",
  "MA in Clinical Counseling",
  "MA in Theological Studies (Advanced)",
  "MA in Theological Studies (Advanced) [Online]",
  "MA in Theological Studies (Online)",
  "Master",
  "Master of Arts",
  "Master of Arts (Online)",
  "Master of Arts in Bible Translation",
  "Master of Arts in Christian Studies (MACS)",
  "Master of Arts in Theological Studies (MATS)",
  "Master of Arts in Theology (Online)",
  "Master of Biblical Studies",
  "Master of Divinity",
  "Master of Divinity (Distance Education)",
  "Master of Divinity (Distance Learning)",
  "Master of Divinity (DL)",
  "Master of Divinity (English-Campus based program)",
  "Master of Divinity (English-Res & Modular)",
  "Master of Divinity (English-Res)",
  "Master of Divinity (English-Residential)",
  "Master of Divinity (English)",
  "Master of Divinity (evening college)",
  "Master of Divinity (Ext)",
  "Master of Divinity (Extn)",
  "Master of Divinity (Hybrid-English)",
  "Master of Divinity (Online)",
  "Master of Divinity (Res & DL)",
  "Master of Divinity (Res & Semi-Res)",
  "Master of Divinity (Residential)",
  "Master of Divinity in Biblical Studies",
  "Master of Divinity in Christian Counseling",
  "Master of Divinity in Christian Ministry",
  "Master of Divinity in Missions",
  "Master of Divinity in New Testament",
  "Master of Divinity in Old Testament",
  "Master of Theology",
  "Master of Theology (DL)",
  "Master of Theology in Christian Ethics",
  "Master of Theology in Christian History",
  "Master of Theology in Christian Theology",
  "Master of Theology in Church History",
  "Master of Theology in History of Christianity",
  "Master of Theology in Missiology",
  "Master of Theology in Mission & Ministry",
  "Master of Theology in Mission Studies",
  "Master of Theology in New Testament",
  "Master of Theology in Old Testament",
  "Master of Theology in Pastoral Care & Counselling",
  "Master of Theology in Pastoral Counseling",
  "Master of Theology in Pastoral Theology",
  "Master of Theology in Pastoral Theology & Counseling",
  "Master of Theology in Practical Theology",
  "Master of Theology in Religion and Philosophy (DL)",
  "Master of Theology-Integrated",
  "PG Dip in Biblical Studies",
  "PG Diploma",
  "PG Diploma (Online)",
  "PhD in Intercultural Studies",
  "PhD in New Testament",
  "PhD in Theology",
  "Postgraduate"
];

export const PREVIOUS_PROGRAMS_BY_CATEGORY: Record<string, string[]> = {
  "Certificate": [
    "Certificate",
    "Certificate in Ministry",
    "Certificate in Pracharak Studies (Hindi)",
    "Certificate in Theology",
    "Certificate in Theology (Hindi)",
    "Certificate in Theology (Res-English)",
    "Certificate of Theology"
  ],
  "Diploma": [
    "Diploma",
    "Diploma in Christian Ministry",
    "Diploma in Christian Ministry (English & Tamil)",
    "Diploma in Theology",
    "Diploma in Theology (English & Kannada)",
    "Diploma in Theology (English-Campus based program)",
    "Diploma in Theology (English-Residential)",
    "Diploma in Theology (English)",
    "Diploma in Theology (Hindi & English)",
    "Diploma in Theology (Malayalam & English)",
    "Diploma in Theology (Malayalam)",
    "Diploma in Theology (Marati)",
    "Diploma in Theology (Res-English)",
    "Diploma in Theology (Res-Telugu)",
    "Diploma in Theology (Residential)",
    "Diploma in Theology (Tamil-Res & Extn)",
    "Diploma in Theology (Tamil)",
    "Diploma in Theology (Telugu & English)"
  ],
  "Bachelor": [
    "B.A in Christian Ministry & Leadership",
    "B.R.E",
    "Bachelor",
    "Bachelor of Arts",
    "Bachelor of Arts in Christian Music",
    "Bachelor of Ministry (Distance Education)",
    "Bachelor of Theology",
    "Bachelor of Theology (Bi-Lingual - English/Hindi)",
    "Bachelor of Theology (Bi-lingual English & Hindi)",
    "Bachelor of Theology (Bi-lingual)",
    "Bachelor of Theology (Distance Education)",
    "Bachelor of Theology (Distance Learning)",
    "Bachelor of Theology (English-Campus based program)",
    "Bachelor of Theology (English-Res)",
    "Bachelor of Theology (English-Residential)",
    "Bachelor of Theology (English)",
    "Bachelor of Theology (Evening College)",
    "Bachelor of Theology (Malayalam, English)",
    "Bachelor of Theology (Malayalam)",
    "Bachelor of Theology (Non-residential)",
    "Bachelor of Theology (Regular)",
    "Bachelor of Theology (Res & Non-Res)",
    "Bachelor of Theology (Res-Bilingual [Eng & Telu])",
    "Bachelor of Theology (Res-English)",
    "Bachelor of Theology (Res)",
    "Bachelor of Theology (Residential)",
    "Bachelor of Theology (Tamil-Res & Modular)",
    "Bachelor of Theology (Tamil)",
    "Bachelor of Theology (Telugu & English)"
  ],
  "Master of Arts": [
    "M.R.E",
    "MA (online)",
    "MA in Christian Studies",
    "MA in Christian Studies (Online)",
    "MA in Clinical Counseling",
    "MA in Theological Studies (Advanced)",
    "MA in Theological Studies (Advanced) [Online]",
    "MA in Theological Studies (Online)",
    "Master",
    "Master of Arts",
    "Master of Arts (Online)",
    "Master of Arts in Bible Translation",
    "Master of Arts in Christian Studies (MACS)",
    "Master of Arts in Theological Studies (MATS)",
    "Master of Arts in Theology (Online)"
  ],
  "Master of Biblical Studies": [
    "Master of Biblical Studies"
  ],
  "Master of Divinity": [
    "Master of Divinity",
    "Master of Divinity (Distance Education)",
    "Master of Divinity (Distance Learning)",
    "Master of Divinity (DL)",
    "Master of Divinity (English-Campus based program)",
    "Master of Divinity (English-Res & Modular)",
    "Master of Divinity (English-Res)",
    "Master of Divinity (English-Residential)",
    "Master of Divinity (English)",
    "Master of Divinity (evening college)",
    "Master of Divinity (Ext)",
    "Master of Divinity (Extn)",
    "Master of Divinity (Hybrid-English)",
    "Master of Divinity (Online)",
    "Master of Divinity (Res & DL)",
    "Master of Divinity (Res & Semi-Res)",
    "Master of Divinity (Residential)",
    "Master of Divinity in Biblical Studies",
    "Master of Divinity in Christian Counseling",
    "Master of Divinity in Christian Ministry",
    "Master of Divinity in Missions",
    "Master of Divinity in New Testament",
    "Master of Divinity in Old Testament"
  ],
  "Master of Theology": [
    "Master of Theology",
    "Master of Theology (DL)",
    "Master of Theology in Christian Ethics",
    "Master of Theology in Christian History",
    "Master of Theology in Christian Theology",
    "Master of Theology in Church History",
    "Master of Theology in History of Christianity",
    "Master of Theology in Missiology",
    "Master of Theology in Mission & Ministry",
    "Master of Theology in Mission Studies",
    "Master of Theology in New Testament",
    "Master of Theology in Old Testament",
    "Master of Theology in Pastoral Care & Counselling",
    "Master of Theology in Pastoral Counseling",
    "Master of Theology in Pastoral Theology",
    "Master of Theology in Pastoral Theology & Counseling",
    "Master of Theology in Practical Theology",
    "Master of Theology in Religion and Philosophy (DL)",
    "Master of Theology-Integrated"
  ],
  "Postgraduate": [
    "PG Dip in Biblical Studies",
    "PG Diploma",
    "PG Diploma (Online)",
    "Postgraduate"
  ],
  "Doctoral": [
    "Doctor of Ministry",
    "Doctor of Ministry (DL)",
    "Doctor of Ministry (Online)",
    "Doctor of Philosophy (Integrated)",
    "Doctor of Philosophy (PhD)",
    "Doctor of Theology",
    "Doctoral",
    "Integrated PhD",
    "PhD in Intercultural Studies",
    "PhD in New Testament",
    "PhD in Theology"
  ]
};

export const ALL_PREVIOUS_PROGRAM_OPTIONS: string[] = Array.from(
  new Set(Object.values(PREVIOUS_PROGRAMS_BY_CATEGORY).flat())
);
